CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE resources (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(128) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_resources_title UNIQUE (title)
);

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    resource_id BIGINT       NOT NULL,
    action      VARCHAR(16)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);


